USE ease;

CREATE TABLE metricClickOnApp (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  app_id INT(10) UNSIGNED NOT NULL,
  year INT(10) UNSIGNED NOT NULL,
  week_of_year TINYINT UNSIGNED NOT NULL,
  day_0 SMALLINT UNSIGNED NOT NULL,
  day_1 SMALLINT UNSIGNED NOT NULL,
  day_2 SMALLINT UNSIGNED NOT NULL,
  day_3 SMALLINT UNSIGNED NOT NULL,
  day_4 SMALLINT UNSIGNED NOT NULL,
  day_5 SMALLINT UNSIGNED NOT NULL,
  day_6 SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);