CREATE TABLE IMPORTED_ACCOUNT (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255),
  website_id INT(10) UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (website_id) REFERENCES websites(id)
);

CREATE TABLE IMPORTED_ACCOUNT_INFORMATION (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  imported_account_id INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (imported_account_id) REFERENCES IMPORTED_ACCOUNT(id)
);

INSERT INTO IMPORTED_ACCOUNT VALUES (NULL, "test", "https://test.test", NULL);
INSERT INTO IMPORTED_ACCOUNT_INFORMATION VALUES (NULL, "login", "easetester1@gmail.com", 1);