CREATE TABLE ONBOARDING_CUSTOMER_INFORMATION (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  teamName VARCHAR(255) NOT NULL,
  teamSize SMALLINT UNSIGNED NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  planId TINYINT UNSIGNED NOT NULL,
  teamCreationLink TEXT,
  transferOwnershipLink TEXT,
  creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastUpdateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);