ALTER TABLE teamUsers
  CHANGE COLUMN arrivalDate creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE teamUsers
  ADD COLUMN arrival_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE teamUsers
SET arrival_date = creation_date;

ALTER TABLE teams
  ADD COLUMN extra_members SMALLINT UNSIGNED NOT NULL DEFAULT 0;

CREATE TABLE TEAM_EMAIL_INVITED (
  id      INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  team_id INT(10) UNSIGNED NOT NULL,
  email   VARCHAR(255)     NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (team_id) REFERENCES teams (id),
  UNIQUE (team_id, email)
);