ALTER TABLE teamUsers
  CHANGE COLUMN arrivalDate creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE teamUsers
  ADD COLUMN arrival_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE teamUsers
SET arrival_date = creation_date;
ALTER TABLE teams
  ADD COLUMN extra_members SMALLINT UNSIGNED NOT NULL DEFAULT 0;