CREATE TABLE WEEKLY_STATS (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  year INT(10) UNSIGNED NOT NULL,
  week_of_year TINYINT(3) UNSIGNED NOT NULL,
  new_companies INT(10) UNSIGNED NOT NULL,
  new_users INT(10) UNSIGNED NOT NULL,
  new_apps INT(10) UNSIGNED NOT NULL,
  new_team_apps INT(10) UNSIGNED NOT NULL,
  passwords_killed INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);