CREATE TABLE EASE_EVENT (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT(10) UNSIGNED,
  team_id INT(10) UNSIGNED,
  name VARCHAR(255) NOT NULL,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  year INT(10) UNSIGNED NOT NULL,
  week_of_year SMALLINT UNSIGNED NOT NULL,
  day_of_year SMALLINT UNSIGNED NOT NULL,
  data TEXT,
  PRIMARY KEY (id)
);