CREATE TABLE EASE_EVENT (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT(10) UNSIGNED,
  team_id INT(10) UNSIGNED,
  name VARCHAR(255) NOT NULL,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data TEXT,
  PRIMARY KEY (id)
);