DROP TABLE UPDATE_ACCOUNT_INFORMATION, EASE_UPDATE, UPDATE_ACCOUNT;

CREATE TABLE UPDATE_ACCOUNT (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE UPDATE_ACCOUNT_INFORMATION (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_account_id INT(10) UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  value TEXT NOT NULL,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (update_account_id) REFERENCES UPDATE_ACCOUNT(id)
);

CREATE TABLE EASE_UPDATE (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT(10) UNSIGNED NOT NULL,
  website_id INT(10) UNSIGNED,
  url VARCHAR(2000),
  update_account_id INT(10) UNSIGNED NOT NULL,
  app_id INT(10) UNSIGNED,
  team_card_id INT(10) UNSIGNED,
  team_user_id INT(10) UNSIGNED,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (website_id) REFERENCES websites(id),
  FOREIGN KEY (update_account_id) REFERENCES UPDATE_ACCOUNT(id),
  FOREIGN KEY (app_id) REFERENCES apps(id),
  FOREIGN KEY (team_card_id) REFERENCES teamCards(id),
  FOREIGN KEY (team_user_id) REFERENCES teamUsers(id)
);

UPDATE notifications SET icon = CONCAT ('https', SUBSTRING(icon, 5)) WHERE icon LIKE 'http://%';
